### ISSUE TITLE
minor errors in JPLab manual

### ISSUE THREAD

**Issue by ecuk** [patheros/JPManuals#3]
Here are a few minor errors I found while reading the PDF JPLab manual today:

- page 11: under number 7, I count 32 note blocks, not 16
- page 11: under number 8, extra mode is described on page 13, not page 7
- page 25: number 10 should be number 9 (as it already is in the image)
- page 27: in the image, the labels for 1, 2 and 3 do not line up correctly with what is being described

Edit: There is also an issue with most of the images of the Four Track. The Gate and CV-V/Oct inputs and outputs are reversed from those of the released version—at least on mac-x64—in the images on pages 3, 9, 10 and 11 (but not 15).

**Comment by patheros** [comment]
Thanks for the feedback. These should all be addressed now.
