### ISSUE TITLE
Improv Jr: Pasted Sequence does not persist after switching pools

### ISSUE THREAD

**Issue by Deadairx** [patheros/JPManuals#8]
On the Improv Jr module, when I copy a sequence from one pool and paste it into another, I expect that sequence to save in that pool. But when I switch away and back, all the CVs are missing. it seems only the rhythm is preserved.

Version: `2.0.2`
VCV Rack Pro `2.4.1`
OS: `macOS ARM64`

![2023-10-31 10 17 09](https://github.com/patheros/JPManuals/assets/12243529/a13a0922-55e7-47cb-8c58-60bdc2dcc7c4)

**Comment by Deadairx** [comment]
Thinking about it, this is probably related to #7

**Comment by joopvdl** [comment]
It's indeed the same issue as #7.
And it's desired behaviour.

First, you are mixing up note pool and sequence. The note pool is the amount of purple notes on the keyboard.
The sequence is the melody you see in the blocks.
Improv behaves differently than most sequencers. Basically, the idea of Improv is to create a note pool (a set of desired notes) and have Improv create a melody with those notes (an improvisation, so to speak).
Improv Jr will create a new sequence from the available notes in the pool (the purple ones) every time you select the note pool.
So if you have an empty pool, you will get no notes.
Preservation of sequences is not supported in Improv Jr. It is in Improv (the full version)

in this video, you copy a sequence (not a note pool) to an empty note pool. So the pool stays empty.
So next time you select that pool, there will be no sequence.
There is some inconsistency in the rhythm being preserved, but in practice, that doesn't make a difference.

**Comment by Deadairx** [comment]
Ah, that makes sense, thank you. I will close these two issues :)
